#!/usr/bin/env bash
# Configure Nginx to have a custom HTTP response header
# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

HOST_NAME=$(hostname)
HEADER="\n\tadd_header X-Served-By $HOST_NAME;"
FIND=$(grep "X-Served-By" /etc/nginx/sites-available/default)

if [[ -z $FIND ]]; then
    sudo sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

sudo service nginx restart