#!/usr/bin/env bash
# Configure Nginx to run and listen on port 80
apt-get update -y
apt-get install -y nginx
sed -i 's/listen [0-9]*/listen 80/g' /etc/nginx/sites-available/default
service nginx restart