#!/usr/bin/env bash
# Script that configures a new Ubuntu machine by installing Nginx and setting up an index page

apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
