#!/usr/bin/env bash
# Script that configures Nginx to perform a 301 redirect for /redirect_me

# Update and install Nginx
apt-get update -y
apt-get install -y nginx

# Insert the redirection block right after "listen 80 default_server;" in the default site config
sudo sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Test configuration and restart nginx
sudo service nginx restart